name: Build image and push to ACR

on:
  push:
    tags:
      - '*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write

        environment: production
        steps:
        - name: 'Checkout repository'
          uses: actions/checkout@v3

        - name: 'Set RELEASE_VERSION'
          run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          
        - name: 'Log in to the container registry'
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and push Docker image
          uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
          with:
            context: .
            push: true
            tags: ${{ env.REGISTRY }}/mood/web:${{ env.RELEASE_VERSION }}
